[package]
name = "zellij-client"
version = "0.40.0"
authors = ["Kunal Mohan <kunalmohan99@gmail.com>"]
edition = "2021"
description = "The client-side library for Zellij"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.8.8", features = ['os-ext'] }
serde = { version = "1.0", features = ["derive"] }
url = { version = "2.2.2", features = ["serde"] }
serde_yaml = "0.8"
serde_json = "1.0"
zellij-utils = { path = "../zellij-utils/", version = "0.40.0" }
log = "0.4.17"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.52.0"
features = [ "Win32_Foundation", "Win32_System_Console" ]

[dev-dependencies]
insta = "1.6.0"

[features]
unstable = []
